version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: exchange_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    depends_on:
      - db
    ports:
      - "12345:12345"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/exchange_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: passw0rd
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
